{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.2.0/mealz-shared-analytics-4.2.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.2.0.klib",
          "size": 53393,
          "sha512": "211af13a67d2cb678b5d27d20f787ff108e6281770050f4db45b536ff5694ba62d2c094485613c160614e47129a6d65d944af06246da26824cf5e8c238c87f00",
          "sha256": "ef33c45a62408fc7a2dc441a3c5ed67bcb554fafd7a734486676798db3ac0ed5",
          "sha1": "2e570811c95e1630816551cabef174cd7fccb430",
          "md5": "eb1e71ae661d8f3aa61f4f6e161dfd4f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.2.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.2.0-metadata.jar",
          "size": 4911,
          "sha512": "e334b9f807e9768ed6f5e2847e7faa9dd3ef5b167e9c2a5a03c23cb6412870c6c2ead4de59d7ef79cfcd06715492b04f3786e34524218fac4aaea046140ca9ff",
          "sha256": "af720049f0cf1721c1fd37882579bc7776fd0f01c10aadbdc51689f6fcc5da6c",
          "sha1": "76ca387603b472d5cbc51db87b08973ce12cf237",
          "md5": "4c69d2c1dcb515721c086cdf88787cea"
        }
      ]
    }
  ]
}
