{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-1.0.0.klib",
          "url": "mealz-shared-analytics-js-1.0.0.klib",
          "size": 47316,
          "sha512": "7791f34b6a62cb69a82ab3c39b43e8036b988764f7ba075a5765cc3027edc0f97c6c6188b510ee3bbd83eef658e49013ca223717db458992170cebdd8e5ba4d2",
          "sha256": "8c0f04d38d0ca1a637f64fb7cbf6c159e61a990b7f85f8c2de3b1cd762fbef31",
          "sha1": "2f5403c08c09645415ebe498428f0c90fd446b92",
          "md5": "ae3c7cdb156e59e77d6424d82ca37ee3"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-1.0.0.klib",
          "url": "mealz-shared-analytics-js-1.0.0.klib",
          "size": 47316,
          "sha512": "7791f34b6a62cb69a82ab3c39b43e8036b988764f7ba075a5765cc3027edc0f97c6c6188b510ee3bbd83eef658e49013ca223717db458992170cebdd8e5ba4d2",
          "sha256": "8c0f04d38d0ca1a637f64fb7cbf6c159e61a990b7f85f8c2de3b1cd762fbef31",
          "sha1": "2f5403c08c09645415ebe498428f0c90fd446b92",
          "md5": "ae3c7cdb156e59e77d6424d82ca37ee3"
        }
      ]
    }
  ]
}
