{
  "formatVersion": "1.1",
  "component": {
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-4.7.0.jar",
          "url": "mealz-shared-analytics-4.7.0.jar",
          "size": 11300,
          "sha512": "78f0f203fca503ababa62d14d30ef1261869ff38fa037c690819522da71845b457f65ba8c0ef63d0a5b3e89202ceb77e0c80ec38c029621aaa93c60662b8f061",
          "sha256": "7199eec854fd7030e46e928c6548cd843f0fb4f74bd1276f77f3fa85fca3094a",
          "sha1": "720ceae1b8400cfb821ed2d805273c03fb005f04",
          "md5": "b58e06339d10ba1d23c429260dc4ad4f"
        }
      ]
    },
    {
      "name": "debugApiElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android-debug/4.7.0/mealz-shared-analytics-android-debug-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android-debug",
        "version": "4.7.0"
      }
    },
    {
      "name": "debugRuntimeElements-published",
      "attributes": {
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android-debug/4.7.0/mealz-shared-analytics-android-debug-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android-debug",
        "version": "4.7.0"
      }
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android/4.7.0/mealz-shared-analytics-android-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android",
        "version": "4.7.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-android/4.7.0/mealz-shared-analytics-android-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-android",
        "version": "4.7.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosarm64/4.7.0/mealz-shared-analytics-iosarm64-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosarm64",
        "version": "4.7.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosarm64/4.7.0/mealz-shared-analytics-iosarm64-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosarm64",
        "version": "4.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iossimulatorarm64/4.7.0/mealz-shared-analytics-iossimulatorarm64-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iossimulatorarm64",
        "version": "4.7.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iossimulatorarm64/4.7.0/mealz-shared-analytics-iossimulatorarm64-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iossimulatorarm64",
        "version": "4.7.0"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosx64/4.7.0/mealz-shared-analytics-iosx64-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosx64",
        "version": "4.7.0"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-iosx64/4.7.0/mealz-shared-analytics-iosx64-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-iosx64",
        "version": "4.7.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-js/4.7.0/mealz-shared-analytics-js-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-js",
        "version": "4.7.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../mealz-shared-analytics-js/4.7.0/mealz-shared-analytics-js-4.7.0.module",
        "group": "ai.mealz.analytics",
        "module": "mealz-shared-analytics-js",
        "version": "4.7.0"
      }
    }
  ]
}
