{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.0.0/mealz-shared-analytics-4.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.0.0.klib",
          "url": "mealz-shared-analytics-js-4.0.0.klib",
          "size": 53054,
          "sha512": "4d762dc50511772d3c2b50d033f4fe3de481cf81318fa59d427cb70f08b4d82909269d0ad91fb19e88e651538056f16b8435f8843961688294bbca5876fe51b9",
          "sha256": "9bd288f473ba6ce305150e26997b6928dccea4f26a271e8bb38b1afdd7fcb908",
          "sha1": "b690309eaa141a15aebf36ab7cd5c96dd0ca6b38",
          "md5": "7b72cd937dd134894e25af46591ce9de"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.0.0.klib",
          "url": "mealz-shared-analytics-js-4.0.0.klib",
          "size": 53054,
          "sha512": "4d762dc50511772d3c2b50d033f4fe3de481cf81318fa59d427cb70f08b4d82909269d0ad91fb19e88e651538056f16b8435f8843961688294bbca5876fe51b9",
          "sha256": "9bd288f473ba6ce305150e26997b6928dccea4f26a271e8bb38b1afdd7fcb908",
          "sha1": "b690309eaa141a15aebf36ab7cd5c96dd0ca6b38",
          "md5": "7b72cd937dd134894e25af46591ce9de"
        }
      ]
    }
  ]
}
