{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.14.0/mealz-shared-analytics-4.14.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.14.0.klib",
          "size": 58585,
          "sha512": "80c732d96f5d4a259cca23b81478c571ed131813630c53d27dcf98dc757e8db1e75233f2fa627da0dea26233981277c623365ad91a9da1fc3aa8a54b8d84387a",
          "sha256": "c95c3bcafd3e0a6b35763d233234595f0cda942056432c1d7a71ee4033640716",
          "sha1": "2b12c6fd15290b10cbaf55d76fa1525b3949cfc1",
          "md5": "c5d90232b12bb619f4a219def4cd77ce"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.14.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.14.0-metadata.jar",
          "size": 4925,
          "sha512": "2ef7b223692678989c1d07f87004281406790cddd4f537927a933c277b3dc41de086a724cff1bcf2b16820ceb6dbc6e5c0a2297688f9de4dcaf3e7af28c6d05e",
          "sha256": "f6b28392c241a5464c39c452a65136d5d364ae22b086afd728c5a02b397529d9",
          "sha1": "c5d3777b6ed6a12cfba472021c48f606a1a27912",
          "md5": "4a00806e628fd5e33be25a9620b0cfff"
        }
      ]
    }
  ]
}
