{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.0/mealz-shared-analytics-4.13.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.13.0.klib",
          "size": 58398,
          "sha512": "b14d8d22fb0f96ef45b6797fcf2568310bc9ee0aec476463707ce804ffac38b33e4ababfa8bf6e0bed40f164f6813e76ae0b58a87d1a0217ba491051d5990841",
          "sha256": "c10997664750c0c5520ecad284ccf4d7589065912ab761921fb15664a2937f4d",
          "sha1": "037ae9654b9413a6cb9613850b5dbd5c753b351a",
          "md5": "ceddadc10dc6d4bb4ac1968ef3f07a18"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.13.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.13.0-metadata.jar",
          "size": 4925,
          "sha512": "ada39ac46480a04c9933edfc73fb4736664ba5299847e68c2ff9ed116f2ff2a9a26f91694722b9879f5e6951711abf64efdb36841dd3f07c0aedd848a10f518a",
          "sha256": "cf8326d1b6ad3ff963d9cf71a8b9e6275d4998626c6ca922f5d35c4d1f36005d",
          "sha1": "9ad84d9c975fc161f4fe165649b7ae3e28b2a532",
          "md5": "5dc4c714968519d8a6f1988a8be59d87"
        }
      ]
    }
  ]
}
