{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.1/mealz-shared-analytics-4.3.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.3.1.klib",
          "size": 54386,
          "sha512": "d68fb5b1f90c349c4309b5d8d07e6c50e30eb03331442ff7911eb3145d0a7f826888a27d8d63d6ada0c268eeb9b506bd7c632419f0526eb490fbd1142956f3f3",
          "sha256": "218486539db9cbf54cec9d6cac644e27279a7ae0b7bc135f12a6a04290361f27",
          "sha1": "68a56990db9ab6316c368f2060bf0e2e214b349c",
          "md5": "76eb50395333711f5f66bd972823be70"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.3.1-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.3.1-metadata.jar",
          "size": 4911,
          "sha512": "dd4f9fba0c5fbbc621c81fba819335cb6a4f3c5e138775e0bcdae895cb2fb4e13dbbd8e7e6ce23f90a75229690cfb9f55dde555ef7de3a69dd9749a0b03b51c4",
          "sha256": "63d81bd3e4255914bb5bc270ab1fcf86a6a98863d1ae03c5dc91f465c088eafe",
          "sha1": "832e4cc6d74054704cc7065c16f6ce5d75ba55eb",
          "md5": "44d79a17989d5d593a266db6d7514b65"
        }
      ]
    }
  ]
}
