{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.2/mealz-shared-analytics-4.7.2.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.7.2.klib",
          "size": 58221,
          "sha512": "9c5a731c15a85b6f957b5131360b21f2226170525a9249af714455c6208c49b1d835e57a7ac3b8b11c5aca3dc9a0085454d64042e17a4715747defc24db9a46a",
          "sha256": "44b28e6d341158826a9e1430073f59d9b17539219c69a55edf1a95e5a1193c66",
          "sha1": "5ee70e0eb2b8cf615ab7a6283cf809db3ae9142b",
          "md5": "fc5a0b269153750da246ce2329b931fd"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.7.2-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.7.2-metadata.jar",
          "size": 4925,
          "sha512": "3c457c5b9982855d8b4d47617d4b687d720eac874a8551b0d477be89eb7e5a32e2488885ee35eaee9588bf2545501630b64699d8b88c8f81b2622d27fb519d93",
          "sha256": "0b55f4326104e28fa3e44dd14056324a485f5087bc4152a22b653dc0884f59e0",
          "sha1": "29b10f216266e3deb4851ccc47e6c835b503ddfa",
          "md5": "230a4faf8cc250f76da219c9c12933c9"
        }
      ]
    }
  ]
}
