{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.0/mealz-shared-analytics-4.3.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.3.0.klib",
          "size": 54255,
          "sha512": "e5010d2ae3c3d957696f9cd364b3efc89fc1a2018dc44c167ab9bfe98af39641ccb045ae4f1a5f96b8daea1784c56a2d1c8a19ca905b67a0bb3acecdb31c0a16",
          "sha256": "f56578b65b0d9b8791b8a7203b7718a37f93cd827153ba142b6a1fbaeabad375",
          "sha1": "b79c7ed6947edf176bf4e713df0bb3004708101a",
          "md5": "04b92dc9b36923d55e3485a54a79cce8"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.3.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.3.0-metadata.jar",
          "size": 4911,
          "sha512": "574b461eaf5a617ef688ca89b76d70464469e0d62ef960786c219c605c67f69833af9c90e72a41d6a9a2b6f1b0fc181556ab7c2d8a7a6eb05eb6c168fe4cbc3e",
          "sha256": "ee3cd6790141e42cbdab77b8e85c058e1320f06dacaa5b41f1e36aaf47fb8942",
          "sha1": "ad44f41d4fef10c19121558286d397199be6d0a5",
          "md5": "9c8b0d205767c835028fa96a04b4e3b1"
        }
      ]
    }
  ]
}
