{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.1/mealz-shared-analytics-4.13.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.13.1.klib",
          "size": 58522,
          "sha512": "9589f9fde202ce015414f99f44f6f88bc6d58b1d310bcfeb6d9d7cdf601a5158fbbf83b34e8de5dbbba3905bd08bda74b3c420d8722ea68d88b334bec4d73e2d",
          "sha256": "717f042a9ada5147b9a869c56fcf6080a65287a990a8ff794882c6fcf03c4411",
          "sha1": "b7c56d8e44d96f76945e93d24608fc626b83eca0",
          "md5": "ffc1f52c62560760688553df373ef1a1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.13.1-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.13.1-metadata.jar",
          "size": 4925,
          "sha512": "7e8bbd2135a50315565501a72a7beaca5045af3652dae4b2389e648cb741f92deb76495b20e127f093090691d09e5b50d234beb9e7db5d22b7820849d877a186",
          "sha256": "64a5f5e6b040ab88b68b80c02c0cd0e804a561f594456021804b007c3d84e0c2",
          "sha1": "494ef8b88bebb32b6d4f93cbe9d6b1f5f8257b01",
          "md5": "0d88633f17a5aaf4f7cdf5a4b2f6f56a"
        }
      ]
    }
  ]
}
