{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.1.0/mealz-shared-analytics-4.1.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.1.0.klib",
          "size": 53109,
          "sha512": "eb9cc20429eb5cf02c2aad4efa09944eeb2bccf0c3f6c4636ef4235955c9735a4c40fe9856cbd8afeef093cf25b14ed48d9b63614ab015707cdd4651c8460f74",
          "sha256": "ee05098f2cc5d82900d7294420f3c99c35ac0cb22543e5f7a43de34997647bbb",
          "sha1": "3a1b7906be4cad57a54a8eda0151a90b60f29658",
          "md5": "76585cb23a6ad336ea7d9cc963865ce5"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.1.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.1.0-metadata.jar",
          "size": 4911,
          "sha512": "c1383f3939885be18e775869ac456f9d4c7aaeb50ef06c65ef5d269261f662dec7b874e8587bb522e754b633eaa4dbed3989094039364e0be14e18ab99348291",
          "sha256": "6d91c5175a7f7d641e828241ca032a458d51756101e18bb0e6bce13766669e14",
          "sha1": "f86e705ebc6234084516eb372d12993ef569e15f",
          "md5": "0dbd2663234748d453eff19fb6a26e93"
        }
      ]
    }
  ]
}
