{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.4.1/mealz-shared-analytics-4.4.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.4.1.klib",
          "url": "mealz-shared-analytics-js-4.4.1.klib",
          "size": 52762,
          "sha512": "8a676d13866e68b92f266ad11015398eed41f35111aac45b016b04822b7dd82c6a1f28d996a0f0e4765f2d09a3b32dc8fc245b828f3605571ef791d97eb15f2d",
          "sha256": "a19326b79c5d224d2a84a97dd1a46ab04174defbc488f3f033e11466e4601f08",
          "sha1": "ac2eed5ee5328f19fd4de098272f48b7c3924f44",
          "md5": "c20f721f80d7b48509ff95984360887e"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.4.1.klib",
          "url": "mealz-shared-analytics-js-4.4.1.klib",
          "size": 52762,
          "sha512": "8a676d13866e68b92f266ad11015398eed41f35111aac45b016b04822b7dd82c6a1f28d996a0f0e4765f2d09a3b32dc8fc245b828f3605571ef791d97eb15f2d",
          "sha256": "a19326b79c5d224d2a84a97dd1a46ab04174defbc488f3f033e11466e4601f08",
          "sha1": "ac2eed5ee5328f19fd4de098272f48b7c3924f44",
          "md5": "c20f721f80d7b48509ff95984360887e"
        }
      ]
    }
  ]
}
