{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.2/mealz-shared-analytics-4.7.2.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.7.2.klib",
          "size": 58118,
          "sha512": "689ceaae15f54481f4f293de67d1ebfdc224e482212a7bf8a67eba87c0cf68ea945faffd9eafd7b5299a9338441b4cb66f32ad7983157174173322940f80e7b6",
          "sha256": "5ffab15e90619ba5b8bcc59dff900b91ea5703506e6e512f5f6e100cd1ab1c9e",
          "sha1": "55702a73456d02ad05f463a5360987d83e59408a",
          "md5": "602e8e1173dfab22f6451d7466e2c098"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.7.2-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.7.2-metadata.jar",
          "size": 4925,
          "sha512": "3c457c5b9982855d8b4d47617d4b687d720eac874a8551b0d477be89eb7e5a32e2488885ee35eaee9588bf2545501630b64699d8b88c8f81b2622d27fb519d93",
          "sha256": "0b55f4326104e28fa3e44dd14056324a485f5087bc4152a22b653dc0884f59e0",
          "sha1": "29b10f216266e3deb4851ccc47e6c835b503ddfa",
          "md5": "230a4faf8cc250f76da219c9c12933c9"
        }
      ]
    }
  ]
}
