{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.1/mealz-shared-analytics-4.7.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.7.1.klib",
          "size": 58118,
          "sha512": "852e8f86745b99ca14a9a3a57d2b5a680cae5b8bebc659fbe2a587f3b61e63df60287b412b8aa2fec6e0d0da91919fa1f6d9949359e0d77387e03341983ca244",
          "sha256": "5145ae5535ac52d4131a976262ecfbc4a9ce6cfd80098bd9baeb6b905617a2c6",
          "sha1": "237a0f1d64e977ef0cd6381160afbd73c94448b4",
          "md5": "7ac19e68bb5cc08ce0d437fcbf4387cc"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.7.1-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.7.1-metadata.jar",
          "size": 4925,
          "sha512": "de652869478ba1382bcfa1b7c2ded2abb28187c0d4ee42f83bea554aa9fdbada622432845ec856a304008eeba81a3924bf57064eb3d1650437f51aa33c8af647",
          "sha256": "a07bd9ace17caea30e951605795a1c55ceb6d028679b2a1948c53b2d69016d2e",
          "sha1": "94d692e8e4f68b6f21ecfbfb641000633fe80203",
          "md5": "fcf5360e7c116425fb4d7d36b3c670fb"
        }
      ]
    }
  ]
}
