{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.1/mealz-shared-analytics-4.7.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.7.1.klib",
          "size": 58204,
          "sha512": "66d018d710480692bca19aced1f4d79c8276cea55b1934dd10daa0972c7f7da1af56a696ce2a56d31f8e7c1d24f6605200cf38611a776a7eb9c44ae65a5bde46",
          "sha256": "d389b1516d587d8f958239a044289f4b02cef6a52b5b0976c6f3172055f31666",
          "sha1": "e6ca86adc02116124c9cf15fe30479d5c2c7e301",
          "md5": "4ead1f9fe300da4e2ca1128faf17cb3e"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.7.1-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.7.1-metadata.jar",
          "size": 4925,
          "sha512": "de652869478ba1382bcfa1b7c2ded2abb28187c0d4ee42f83bea554aa9fdbada622432845ec856a304008eeba81a3924bf57064eb3d1650437f51aa33c8af647",
          "sha256": "a07bd9ace17caea30e951605795a1c55ceb6d028679b2a1948c53b2d69016d2e",
          "sha1": "94d692e8e4f68b6f21ecfbfb641000633fe80203",
          "md5": "fcf5360e7c116425fb4d7d36b3c670fb"
        }
      ]
    }
  ]
}
