{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.12.0/mealz-shared-analytics-4.12.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.12.0.klib",
          "size": 58386,
          "sha512": "1ee21f16f6f9f72d33be596a693ffdb1f4d018e88624eed92c8947d2c5e46b601e636cb355870edc7fe68006a4fc1835f7bbdb6343baa99e64428e8e02ced5ad",
          "sha256": "38bc6f1daa564c9640e5fd2fc5f0ee62bdfea677eaf1f0e39e80893b8cd4f9c2",
          "sha1": "a2c96b07ae161edb51496668538167f46b0707e3",
          "md5": "c48a39893f6a84f1b6c9aad7388bc40b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.12.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.12.0-metadata.jar",
          "size": 4925,
          "sha512": "6ddb298b37626cfaa947c6d1b5713cdd126d1044977c6686097f720a7d3602e97b849202c961fb0c5f581a9a32d5380f6414dacbf2337e51de6633a68372e044",
          "sha256": "cfb55021e0bb83698dfaff3f34447e4163f70a7df3b804446a79e4c9f2bf6ed5",
          "sha1": "ba0a8c5d607b583dda0ceadefa0b59a0a1e67c77",
          "md5": "285723aed57a1c4d3a513649c3a6d91a"
        }
      ]
    }
  ]
}
