{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.4.1/mealz-shared-analytics-4.4.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.4.1.klib",
          "size": 53376,
          "sha512": "21b9c9b3a1c3a0b7968f965b61ac70f2ea3c9c06efaf1f8bffecd6870c9a1b6a0267ea28d4364fc97a291f5913c12248281ee67c4758492bb2c13c8db22d6770",
          "sha256": "508efa64055c026f5efb6e220ac81d1ca9eb29aaa221b8e32cb77f734c951049",
          "sha1": "45c9e54cdcf98f78f033fbcc1f25312fa66d8337",
          "md5": "55cd19f95915593e8084a9ac20c42de1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.4.1-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.4.1-metadata.jar",
          "size": 4911,
          "sha512": "766f014b041fd346c165aa0b2329ea365ef72b2e2b7bb385dd172eb220bb27b90c31596d19329d1ad1fe448cd9cadafdf3c0b7d55af9bb27745d20784d20cce7",
          "sha256": "eee471477732025c92a036b8f302c50a7357ca6ae84c359bd9a548e8d2c1b17f",
          "sha1": "3e62101510cdda6a9002435bc2aed83fbde56f1f",
          "md5": "5c9ab2dcb952d2319d01c974b5cae304"
        }
      ]
    }
  ]
}
