{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-1.0.0.klib",
          "size": 54641,
          "sha512": "b02f4bed21902690f38339d158b2a4c49d2e2625b46f80faf042c495f500dddeb5436b92fdb3fb97ca4c4861b919ae253558fc8ccc6da18de0d5817a836ea896",
          "sha256": "a8f0a4dedf407c4c9db6a1e0bd65694fda2a2b4782f9972f8c7a8b6df5cfaa11",
          "sha1": "8b3ae9f88cec9e22d922592f2b16b41185877a47",
          "md5": "9892f1a6746be3d6d6bbc98345b66b70"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-1.0.0-metadata.jar",
          "size": 3220,
          "sha512": "7a86b8dd5401b908ebefb2a03a7e7e266830d98f2265f2fd656d53b9c0cbf97e7c1cda2667182931e1fe8a951444ad6a170a6273698977c501fec208b08ed631",
          "sha256": "7e3b204c9827d0452ae598264cb2cc721f32d7f168a547c951798d40f80605bd",
          "sha1": "97ef251313b5eb360b7a8f7fbdf6a721499de336",
          "md5": "85535eeff502f6ef784c707d959e9f4f"
        }
      ]
    }
  ]
}
