{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.12.0/mealz-shared-analytics-4.12.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.12.0.klib",
          "size": 58472,
          "sha512": "c436eff3ce0f387335dba774a5ffb0f15e1bb464acd014416d42fa57bfd5c72850db393addf831aa874495ad4b14c00c498fd539458f8a219f26813373e19c14",
          "sha256": "0388e48a5fe812db54ab29ad9a530dedb72f454615fcd791b4fb4cefa28bf63f",
          "sha1": "c8c6ec125d7d40bce6e8e7249961e6972b4fed6c",
          "md5": "0e4a8d73f09ceb218d5002a0041ab9b7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.12.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.12.0-metadata.jar",
          "size": 4925,
          "sha512": "6ddb298b37626cfaa947c6d1b5713cdd126d1044977c6686097f720a7d3602e97b849202c961fb0c5f581a9a32d5380f6414dacbf2337e51de6633a68372e044",
          "sha256": "cfb55021e0bb83698dfaff3f34447e4163f70a7df3b804446a79e4c9f2bf6ed5",
          "sha1": "ba0a8c5d607b583dda0ceadefa0b59a0a1e67c77",
          "md5": "285723aed57a1c4d3a513649c3a6d91a"
        }
      ]
    }
  ]
}
