{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.1/mealz-shared-analytics-4.3.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.3.1.klib",
          "size": 54403,
          "sha512": "916dea3af0e756b238338dc2bde12109de519428010a6a50b5ea12c655210f5451693be7b700e01477701736504ebe949796c8ea09f230155b16a23c0b8231e4",
          "sha256": "c882f280215159f684bff5375b73bfbfe158d33e7f1aba87ddee15b3f31c54b2",
          "sha1": "61d3474b88d1f3e6424790305455453ce6e5c691",
          "md5": "fb8fee57e7c86fd84eff811ed31bdb0b"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.3.1-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.3.1-metadata.jar",
          "size": 4911,
          "sha512": "dd4f9fba0c5fbbc621c81fba819335cb6a4f3c5e138775e0bcdae895cb2fb4e13dbbd8e7e6ce23f90a75229690cfb9f55dde555ef7de3a69dd9749a0b03b51c4",
          "sha256": "63d81bd3e4255914bb5bc270ab1fcf86a6a98863d1ae03c5dc91f465c088eafe",
          "sha1": "832e4cc6d74054704cc7065c16f6ce5d75ba55eb",
          "md5": "44d79a17989d5d593a266db6d7514b65"
        }
      ]
    }
  ]
}
