{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.1/mealz-shared-analytics-4.3.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.3.1.klib",
          "size": 54255,
          "sha512": "5d00922d592bb0958e0654816f643dd1c1862c2bb0a27a5323bf274c85f63e9b3cc03825dc3114b0205413d5711d9087328af3f7f479f446ebfbf180d7402c89",
          "sha256": "e43564324c100676f86c83f529980981f8cf08fb2f3d453b0474a82f31a8ba37",
          "sha1": "c5bc76aad5b9fc3374d8b4eaf7ada8938933d693",
          "md5": "b6d9e9d7384057fa9d398bf0dfa90ed6"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.3.1-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.3.1-metadata.jar",
          "size": 4911,
          "sha512": "8e2ae563841302ff06efd00a4a9e6bdc85104c97c96a2633594a9180d9d96d1b868d3e2f7485d3e251e4fd8d97061196d61f69a980da605502fe40ba90903ee7",
          "sha256": "3455d2890fb21e16dc36a60623d3e834dcaf8dae9b21c67b70f0ad28e42729e8",
          "sha1": "39490fc69bf38afd658c737811277d7b05224450",
          "md5": "abd786320ffd87d1eccdf1d906106e4b"
        }
      ]
    }
  ]
}
