{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/2.0.0/mealz-shared-analytics-2.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-2.0.0.klib",
          "size": 57151,
          "sha512": "8c336a77c59be3397000f9d75426334f968f98c87f61d9a43eae21b599cf4441afb520731ca7f2ab1931a800d6fa523dd39f85fd99e4662241932473ef835178",
          "sha256": "31ad41015ea3cd1c672663cd86fb109eb1bd8e8f7f1ea626bf76e4b19c8bdaa9",
          "sha1": "e78eaf0ef65e016940be068c71579984e44dd9d2",
          "md5": "82b5bfda584a29e492a771754038f300"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-2.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-2.0.0-metadata.jar",
          "size": 3220,
          "sha512": "6355985bb99ba2b9d93af509dcc5978e2bf3da725d349724e92e6ec38391ff9a84558748eed7cdee230e6735e1e2855c84a600a1c66cd812e850b770266b8dfb",
          "sha256": "28bd077c32808af50aaf7d37e347e59385079f6d9b4187cbbd023b51ed127a23",
          "sha1": "10e4f99845d619f73775958483857976fd30fcff",
          "md5": "fcdc1b594a77ece0c1b6c4d87a39d085"
        }
      ]
    }
  ]
}
