{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-1.0.0.klib",
          "size": 54744,
          "sha512": "9abe3bb311efa3bd354f7a21fe15e2bdd80045b01884f00d459b17c2a0febacabdd9998536dea53140bede7da0d1c0757115bcd4016fb4a2a01f470e31f03021",
          "sha256": "bf286408a6f0f2a17ddeb7b44d3a05cf4cfb80b497ffe42dee5c2cd292897384",
          "sha1": "96e72104e174a0fd61d2d145f013d0873b7882c1",
          "md5": "79eb683a0d21e01fb8555df6373a8ee4"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-1.0.0-metadata.jar",
          "size": 3220,
          "sha512": "7a86b8dd5401b908ebefb2a03a7e7e266830d98f2265f2fd656d53b9c0cbf97e7c1cda2667182931e1fe8a951444ad6a170a6273698977c501fec208b08ed631",
          "sha256": "7e3b204c9827d0452ae598264cb2cc721f32d7f168a547c951798d40f80605bd",
          "sha1": "97ef251313b5eb360b7a8f7fbdf6a721499de336",
          "md5": "85535eeff502f6ef784c707d959e9f4f"
        }
      ]
    }
  ]
}
