{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-1.0.0.klib",
          "size": 53565,
          "sha512": "c72cff104c0de87a43e77efc6f2f7d3a0a20296f211de57288833404be30cdecd72012a2ef756e1d2acda91e17ce8355172dcb70fb8b29db8aa90a368b182713",
          "sha256": "432ac90b69a573a724f1c065384123e52becbd74df2cb5438aa0e4f07cc1c44a",
          "sha1": "c3622c2a7ba718e161198bb578f6f2ee4fde3678",
          "md5": "120986c9388b5d65442ec614e362f980"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-1.0.0-metadata.jar",
          "size": 3242,
          "sha512": "1d9b08c9a7f33f9ddac5c2d16efdc5c83f0371bdb95487c49bbaff0b061d50510b4a657724e3009bf7672511eff342e44205b112d96bdb4c77da1de7c82c9090",
          "sha256": "4aab249e1c2a4a00d823b8ba7d3b20f20cf403411ecb4c7eee8f350f583f87c5",
          "sha1": "22125a00fb0f28e24ec05c63363dfb75d5a87c66",
          "md5": "3f08c8f3c8b8571e382ccae0c01815b3"
        }
      ]
    }
  ]
}
