{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.3.1/mealz-shared-analytics-4.3.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.3.1.klib",
          "size": 54489,
          "sha512": "02696e4c4db84ede171ec1a41adbfee1c5b63c940ccb64951d7cfcdf107031abaf88c1a27264faa9d6842f7b30573e224cb51f73eae441aa30effdf2c56e6be4",
          "sha256": "545db6167c89d77dc5d3bdd15200dc0f6cc39e32479931c524fc2e10b3c29962",
          "sha1": "53ed7a5b4a4bbf9141e150a0cc078449090eb358",
          "md5": "f74d1addafada35d0a1c0cff07082008"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.3.1-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.3.1-metadata.jar",
          "size": 4911,
          "sha512": "dd4f9fba0c5fbbc621c81fba819335cb6a4f3c5e138775e0bcdae895cb2fb4e13dbbd8e7e6ce23f90a75229690cfb9f55dde555ef7de3a69dd9749a0b03b51c4",
          "sha256": "63d81bd3e4255914bb5bc270ab1fcf86a6a98863d1ae03c5dc91f465c088eafe",
          "sha1": "832e4cc6d74054704cc7065c16f6ce5d75ba55eb",
          "md5": "44d79a17989d5d593a266db6d7514b65"
        }
      ]
    }
  ]
}
