{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.4.1/mealz-shared-analytics-4.4.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.4.1.klib",
          "size": 53479,
          "sha512": "f7a8f01b0dbb700cbe83df6f21eb433636c566edb32fb0ccbc00f13184ee802bcee28adc485282191405438b923e6ce6f108cf48d7af9f801cce554478f29826",
          "sha256": "4d754588ea14d55fd6698d1b502318021490a371647909c1b90e544800f1d5df",
          "sha1": "63dbae3b4089ac50f598c664fb0cbcf2c2bd4d53",
          "md5": "002697b582504415bd1e4f36ce588627"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.4.1-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.4.1-metadata.jar",
          "size": 4911,
          "sha512": "766f014b041fd346c165aa0b2329ea365ef72b2e2b7bb385dd172eb220bb27b90c31596d19329d1ad1fe448cd9cadafdf3c0b7d55af9bb27745d20784d20cce7",
          "sha256": "eee471477732025c92a036b8f302c50a7357ca6ae84c359bd9a548e8d2c1b17f",
          "sha1": "3e62101510cdda6a9002435bc2aed83fbde56f1f",
          "md5": "5c9ab2dcb952d2319d01c974b5cae304"
        }
      ]
    }
  ]
}
