{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-1.0.0.klib",
          "size": 56542,
          "sha512": "f9c4235b861dea2aaadd7873750d1e3fdab811512e46c54e7e9d67e587e5f15c023aad3333b9904b15c6336290019091a4dd0a5b2c75be69c16636484618fcbe",
          "sha256": "6b3382db5c9206e26cf133a44c5c8dfba177b52f0e6c0fa35689e0ab6c64602c",
          "sha1": "ee3617166ec60dc1e34df2ab28a5d317ed5aaa18",
          "md5": "3a66fd9dd438a7623231a3c5e6891cbb"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-1.0.0-metadata.jar",
          "size": 3220,
          "sha512": "7a86b8dd5401b908ebefb2a03a7e7e266830d98f2265f2fd656d53b9c0cbf97e7c1cda2667182931e1fe8a951444ad6a170a6273698977c501fec208b08ed631",
          "sha256": "7e3b204c9827d0452ae598264cb2cc721f32d7f168a547c951798d40f80605bd",
          "sha1": "97ef251313b5eb360b7a8f7fbdf6a721499de336",
          "md5": "85535eeff502f6ef784c707d959e9f4f"
        }
      ]
    }
  ]
}
