{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/1.0.0/mealz-shared-analytics-1.0.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-1.0.0.klib",
          "size": 53480,
          "sha512": "430e3c15419e906f7550636b8f94bb7d8c3ae3747375a88d31ceceb56c3f0366b1db74df39878781ed20cb6bddeeadabdde83738abd3a6d7a54b2a2871988921",
          "sha256": "c4ee0ee466979f8fb94403df040edcc608ce1ee447243a38de9d02ca05f6ed56",
          "sha1": "054d638cf3377411e25a0a63e401c3178b4af80f",
          "md5": "0b18c6ed89172c2b453e94a96c2ef4ed"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-1.0.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-1.0.0-metadata.jar",
          "size": 3242,
          "sha512": "1d9b08c9a7f33f9ddac5c2d16efdc5c83f0371bdb95487c49bbaff0b061d50510b4a657724e3009bf7672511eff342e44205b112d96bdb4c77da1de7c82c9090",
          "sha256": "4aab249e1c2a4a00d823b8ba7d3b20f20cf403411ecb4c7eee8f350f583f87c5",
          "sha1": "22125a00fb0f28e24ec05c63363dfb75d5a87c66",
          "md5": "3f08c8f3c8b8571e382ccae0c01815b3"
        }
      ]
    }
  ]
}
