{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.9.0/mealz-shared-analytics-4.9.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.9.0.klib",
          "size": 58268,
          "sha512": "1ea42762e48ba09e467131c31ddcf193da75fa16b05870b7d1b133e6b78e917f499187e695dcb1994a4c33bc633a209153ae409fca6174cc998b2f12f7dbe077",
          "sha256": "3239646e7f6e9ca0839e7cdf13575512e580eed461f55e8fb97811e464410c52",
          "sha1": "b0425b26afd2a9fee230235ec29b7e686e7d8cd3",
          "md5": "6b3b233497bb05793d4b843b28872ead"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.9.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.9.0-metadata.jar",
          "size": 4925,
          "sha512": "d01d84a58edc5ddc85d420af36344b9c4dbe4e9f2aba2f8b2098c55fe31a882fbc964030930b22495596a4bf7178148c3a9f5826303e9796de0efd203ece3b13",
          "sha256": "3ef01ae39964917c9678749180efa6c83c84579a01d7bcf6f9698b4a1f212bbb",
          "sha1": "b5bd719fdd0e94505306a4c8dfbb030637c140e5",
          "md5": "13533f83612ff76650f5fbfed4be5e94"
        }
      ]
    }
  ]
}
