{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.11.0/mealz-shared-analytics-4.11.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.11.0.klib",
          "size": 58357,
          "sha512": "16217bd52760faa3526cfa8520d7c6a4c27cb6d94f4b8aa7cd40a0679c07af71559d238e7757e8f015310dfa6ba72102ef63b1abf9d28a6a15ee897fd0328c8c",
          "sha256": "575ad1f67dc8be5a6e5bd3df7e4222fe61c90c12efb73bac9f3597928356f699",
          "sha1": "7dbc898cc4a8b1c7e2c8c8d5c6da79800f842d57",
          "md5": "47c66a5799a356a090d1c1c1a8d6916a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.11.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.11.0-metadata.jar",
          "size": 4925,
          "sha512": "c131764ecc964ce66cf83b9a258d516ee8a64a28594ff11e2b9f2c61122e8ac63262b55e24c2fb47c95a5b8743a352bf9f217ef843b5824e32a76ad4e0b8dfd4",
          "sha256": "3c767decfae6078d818977cc616b0c82a4d01cc11ed4fc7a56700cf74f5b4e29",
          "sha1": "8a2e66deb9809a6f35c45fef13a84ba2ea6bb26b",
          "md5": "4e30e7ed5b4a7f0c8f50cc001ed4df69"
        }
      ]
    }
  ]
}
