{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.13.1/mealz-shared-analytics-4.13.1.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.13.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.13.1.klib",
          "url": "mealz-shared-analytics-js-4.13.1.klib",
          "size": 57589,
          "sha512": "8c0f0d500d9f8ae77feeb42b22b44c68f2c4f15e5317bfdf021648118a354298ed8b9ada78f199242484ca872c289b8c9b4fc7a3760eb041160b21da3bfc4179",
          "sha256": "501148409f149bf602034a9b5f5ba27ae65416fde123df4db8df48124a9b248f",
          "sha1": "9d1994bd0572348fd4394e24249525e01c1c288f",
          "md5": "9c8460aabd9e60ffe963bca0add5d613"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-js-4.13.1.klib",
          "url": "mealz-shared-analytics-js-4.13.1.klib",
          "size": 57589,
          "sha512": "8c0f0d500d9f8ae77feeb42b22b44c68f2c4f15e5317bfdf021648118a354298ed8b9ada78f199242484ca872c289b8c9b4fc7a3760eb041160b21da3bfc4179",
          "sha256": "501148409f149bf602034a9b5f5ba27ae65416fde123df4db8df48124a9b248f",
          "sha1": "9d1994bd0572348fd4394e24249525e01c1c288f",
          "md5": "9c8460aabd9e60ffe963bca0add5d613"
        }
      ]
    }
  ]
}
