{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.16.0/mealz-shared-analytics-4.16.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.16.0.klib",
          "size": 58777,
          "sha512": "1846793637a8f7cb861094967b3e90ba011a4edeed2f136a36b62f5e5aabb2c134b1b1c3c730d946d775cce9b0f9098398ceed336860b34b596b75f68acb4ac8",
          "sha256": "bfb3ff4a210a3d8ec89049cb0fab23fa2eca5eb0368b248303621d6ca5915c7c",
          "sha1": "1b60f8242829f697a3ffd92976a8ee090f5af50f",
          "md5": "cd36280467d1a1d7d24ba4b45cc6ced5"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.16.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.16.0-metadata.jar",
          "size": 4925,
          "sha512": "89917e1b87a387886912c944741b0f5bccdf13828c536e4501287b34e515cd45adfadeb4230c0e08d1eb0622612c1fefe4317e5eb6f13e83928634989126689a",
          "sha256": "d6e6ae7811fb4eea186d0b34ceb8a044bc4df9e4da1e8e8d304aaed882f8d736",
          "sha1": "6c88701e6aeab538833374f3bca7beeb0c4e4c9c",
          "md5": "d12332cec631387dc186e5d2b3a998c3"
        }
      ]
    }
  ]
}
