{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.4.0/mealz-shared-analytics-4.4.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.4.0.klib",
          "size": 54814,
          "sha512": "0edcd263acedafc6d26c27a54a8bbd19946ff3e0dc7b0c48c2714423a132f6b3ba7cf9f708a6e83f36b3a3478f253be9d8ee8e8dea73d0537a93b40ea00e9b04",
          "sha256": "2f6109912eb1e51b923caedf37beab7a4c82945e077dc10142d4055a2be033c3",
          "sha1": "205b68c04fd999a53d68cc4a5b0bfe98d67f3168",
          "md5": "f1ce4dd18066fe4cfda6fcd30ca5ff5a"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.4.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.4.0-metadata.jar",
          "size": 4911,
          "sha512": "2a7d06cce49d96f7ebde749789cdcc650f5b4de92193a616d007e4dccb1bfe26e765faa051c8e73168df9756ba3990ad92f54cb46442aa11ef3dc0cf84bcdf63",
          "sha256": "84e28892d97fc065e239ad2e3523463e0b8fc055fceb40e9525ed2da9ed51014",
          "sha1": "625197edbbd056cd1d100133043d2eda2737b30f",
          "md5": "84cc70f144a8bc490cba3cc869be50e8"
        }
      ]
    }
  ]
}
