{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.14.0/mealz-shared-analytics-4.14.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosarm64-4.14.0.klib",
          "size": 58602,
          "sha512": "b82d57b9ec0b26f42132a93e097e7cd5f9e35ce2405b4ebac1d89abfdaeb4854f43830d76b61785f698b5b8822a1f9661520d369fa3a5343b8c923a2a165543e",
          "sha256": "777132a0878145c1935e1a062e51432793ed165597c04e2516e29388af2b19a6",
          "sha1": "c29f6682ad170d67960786907d72cd1a1f6b0b1a",
          "md5": "90f481f88148d41ec2bae3e15118aa10"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosarm64-4.14.0-metadata.jar",
          "url": "mealz-shared-analytics-iosarm64-4.14.0-metadata.jar",
          "size": 4925,
          "sha512": "2ef7b223692678989c1d07f87004281406790cddd4f537927a933c277b3dc41de086a724cff1bcf2b16820ceb6dbc6e5c0a2297688f9de4dcaf3e7af28c6d05e",
          "sha256": "f6b28392c241a5464c39c452a65136d5d364ae22b086afd728c5a02b397529d9",
          "sha1": "c5d3777b6ed6a12cfba472021c48f606a1a27912",
          "md5": "4a00806e628fd5e33be25a9620b0cfff"
        }
      ]
    }
  ]
}
