{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.2.0/mealz-shared-analytics-4.2.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.2.0.klib",
          "size": 53376,
          "sha512": "146254597cc4f65f8fbeb0f84738e18258363a4be7b32c900d205b02fef9b32f0ec84b423691d87b042f2c28358d5f1f38bd0e3eb3a539344d19ff769e0d13e8",
          "sha256": "8e6ae28a894c21ff821c9d3bfae3a67c6054bb82bb6ac56d637ef0ff76ffb20c",
          "sha1": "9507ac1cae46534fffae2d98b277adf92fa54d70",
          "md5": "f0ed8ecd7079441c4f5878a3f4b66a41"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.2.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.2.0-metadata.jar",
          "size": 4911,
          "sha512": "e334b9f807e9768ed6f5e2847e7faa9dd3ef5b167e9c2a5a03c23cb6412870c6c2ead4de59d7ef79cfcd06715492b04f3786e34524218fac4aaea046140ca9ff",
          "sha256": "af720049f0cf1721c1fd37882579bc7776fd0f01c10aadbdc51689f6fcc5da6c",
          "sha1": "76ca387603b472d5cbc51db87b08973ce12cf237",
          "md5": "4c69d2c1dcb515721c086cdf88787cea"
        }
      ]
    }
  ]
}
