{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.7.0/mealz-shared-analytics-4.7.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iosx64-4.7.0.klib",
          "size": 57688,
          "sha512": "ebdf402481e79e99b4d369cb4668b86cab0515f7c3f57eb7b1cc5468a8e02d8e01ccba753b635f233714f3ed11d165f77d5ae04d1b0b1be67698ae4374b90f0f",
          "sha256": "f638041e339d6e3acaf29d6d8fa463639ab49e36acb8d4794d3b730169159c62",
          "sha1": "08338b3f76cc95ab93b87d88ec5388f0e9648851",
          "md5": "0dcf1b626659ae8105261080526ab4cd"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iosx64-4.7.0-metadata.jar",
          "url": "mealz-shared-analytics-iosx64-4.7.0-metadata.jar",
          "size": 4925,
          "sha512": "e10a16c4c1c721b13d354ca798a683a66f8266b9199fbfa4734874b97651fce2bb0c0afc877c6edcefa1235213585bd8db375812dc0062ae1c4e7c80549ade04",
          "sha256": "07e8b520221f85cdab194e4f99f954c5afac767db57aa34102b7de4e6cd92fce",
          "sha1": "b5cc5ed6de5044df4293181dc177eb600026b74c",
          "md5": "5d640ec7a497c02a33a9943d8e2ab0fe"
        }
      ]
    }
  ]
}
