{
  "formatVersion": "1.1",
  "component": {
    "url": "../../mealz-shared-analytics/4.1.0/mealz-shared-analytics-4.1.0.module",
    "group": "ai.mealz.analytics",
    "module": "mealz-shared-analytics",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics.klib",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.1.0.klib",
          "size": 53195,
          "sha512": "5ef68c6856c406b0d53be64253a5235da1d61bb124bd5929e2cee8c18ba64f9d5dc02e166b42a60578b695b2a931aa5265d8d2d11d78f06f431a142460e87826",
          "sha256": "d2229cf74fa1f06d5f523045818fd82069d957b9672d2285b87c19d7230066c3",
          "sha1": "c387bc08bf3b1f1b68653546311c6ef944ede946",
          "md5": "892697eccf949aab89673aef60e2e68c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "mealz-shared-analytics-iossimulatorarm64-4.1.0-metadata.jar",
          "url": "mealz-shared-analytics-iossimulatorarm64-4.1.0-metadata.jar",
          "size": 4911,
          "sha512": "c1383f3939885be18e775869ac456f9d4c7aaeb50ef06c65ef5d269261f662dec7b874e8587bb522e754b633eaa4dbed3989094039364e0be14e18ab99348291",
          "sha256": "6d91c5175a7f7d641e828241ca032a458d51756101e18bb0e6bce13766669e14",
          "sha1": "f86e705ebc6234084516eb372d12993ef569e15f",
          "md5": "0dbd2663234748d453eff19fb6a26e93"
        }
      ]
    }
  ]
}
